### ISSUE TITLE
Cannot install on WebStorm at latest version available

### ISSUE THREAD

**Issue by LuigiElleBalotta** [srcn/blue-midnight#1]
Webstorm is at its latest version, but I cannot install this theme as you can see from the screenshot below:

<img width="1211" alt="Schermata 2022-09-28 alle 11 49 40" src="https://user-images.githubusercontent.com/16773213/192748258-013fdf35-6dcf-477e-b8dc-c50c2d0c15c3.png">

> WebStorm 2022.2.2
> Build #WS-222.4167.31, built on September 14, 2022
> Licensed to Ilenia Di Giovanni
> Subscription is active until November 22, 2022.
> For educational use only.
> Runtime version: 17.0.4+7-b469.53 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 12.1
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2048M
> Cores: 12
> Metal Rendering is ON
> Non-Bundled Plugins:
>     net.antelle.intellij-xcode-dark-theme (1.2.4)
>     com.github.copilot (1.1.32.1956)
>     com.intellij.lang.jsgraphql (3.3.0)
>     com.intellij.database (222.4167.31)

Any idea?

**Comment by srcn** [comment]
You need the EAP version; 2022.3 EAP. The new UI is available to public beginning with the 2022.3 EAP so the minimum version of the plugin is set to that version.
